<?php
require_once dirname(__DIR__) . '/_bootstrap.php';

$endpoint = 'VipLevel/GetVipLevelConfig';
$override = api_get_override($endpoint);
if ($override) {
    $decoded = api_json_decode_lenient((string) $override['content']);
    if ($decoded['ok']) {
        $payload = $decoded['data'];
        api_refresh_times($payload);
        api_emit($payload);
    }
}

$payload = [
        'data' => [
            [
                'level' => 0,
                'recharges' => 2000,
                'betCode' => 6000,
                'upgradeRewards' => 0,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 0,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 0,
                'weekReward' => 0,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 1,
                'recharges' => 8000,
                'betCode' => 24000,
                'upgradeRewards' => 3,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 1500,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 600,
                'weekReward' => 3,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 2,
                'recharges' => 40000,
                'betCode' => 120000,
                'upgradeRewards' => 8,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 7500,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 3000,
                'weekReward' => 5,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 3,
                'recharges' => 150000,
                'betCode' => 450000,
                'upgradeRewards' => 15,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 37500,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 12000,
                'weekReward' => 12,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 4,
                'recharges' => 800000,
                'betCode' => 2400000,
                'upgradeRewards' => 40,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 150000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 45000,
                'weekReward' => 25,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 5,
                'recharges' => 2000000,
                'betCode' => 6000000,
                'upgradeRewards' => 200,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 900000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 120000,
                'weekReward' => 80,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 6,
                'recharges' => 2000000,
                'betCode' => 6000000,
                'upgradeRewards' => 700,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 2700000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 300000,
                'weekReward' => 200,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 7,
                'recharges' => 5000000,
                'betCode' => 15000000,
                'upgradeRewards' => 2000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 4500000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 750000,
                'weekReward' => 500,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 8,
                'recharges' => 10000000,
                'betCode' => 30000000,
                'upgradeRewards' => 6000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 9000000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 1800000,
                'weekReward' => 1200,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 9,
                'recharges' => 30000000,
                'betCode' => 90000000,
                'upgradeRewards' => 15000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 21000000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 4500000,
                'weekReward' => 3000,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 10,
                'recharges' => 50000000,
                'betCode' => 150000000,
                'upgradeRewards' => 40000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 52500000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 9000000,
                'weekReward' => 8000,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 11,
                'recharges' => 150000000,
                'betCode' => 450000000,
                'upgradeRewards' => 100000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 105000000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 15000000,
                'weekReward' => 20000,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => -1,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
            [
                'level' => 12,
                'recharges' => -249870000,
                'betCode' => -749870000,
                'upgradeRewards' => 250000,
                'mothRelegationRecharges' => 0,
                'mothRelegationBetCode' => 262500000,
                'mothRewardRecharges' => 0,
                'mothRewardBetCode' => 0,
                'mothReward' => 0,
                'weekRewardRecharges' => 0,
                'weekRewardBetCode' => 30000000,
                'weekReward' => 50000,
                'dayWithdrawAmount' => -1,
                'dayWithdrawCount' => 20,
                'dayWithdrawNoFeeCount' => 0,
                'feePercent' => 0,
                'fee' => 0,
            ],
        ],
        'code' => 0,
        'msg' => 'Succeed',
        'msgCode' => 0,
        'serverTime' => 1780315434027,
    ];

api_refresh_times($payload);
api_emit($payload);
