{
    "data": [
        {
            "id": 300341,
            "sysLanguage": "en",
            "type": 4,
            "imageUrl": "/img/6006/other/020610946-31053-file_20260413140610878.webp",
            "title": "",
            "content": "",
            "sort": 888,
            "jumpUrl": "",
            "buttonTxt": "",
            "messageJumpType": 0,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1776089174328
        },
        {
            "id": 300471,
            "sysLanguage": "en",
            "type": 4,
            "imageUrl": "/img/6006/other/035247333-40491-file_20260515155246378.webp",
            "title": "",
            "content": "",
            "sort": 777,
            "jumpUrl": "https://dhani.help/bonus",
            "buttonTxt": "",
            "messageJumpType": 1,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1779383091135
        },
        {
            "id": 300469,
            "sysLanguage": "en",
            "type": 4,
            "imageUrl": "/img/6006/other/071633131-38186-file_20260510071632294.webp",
            "title": "",
            "content": "",
            "sort": 666,
            "jumpUrl": "https://dhanivip.pages.dev/",
            "buttonTxt": "",
            "messageJumpType": 1,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1778860719437
        },
        {
            "id": 300343,
            "sysLanguage": "en",
            "type": 4,
            "imageUrl": "/img/6006/other/020629876-31054-file_20260413140629821.webp",
            "title": "",
            "content": "",
            "sort": 555,
            "jumpUrl": "https://t.me/dhaniwinbot",
            "buttonTxt": "",
            "messageJumpType": 1,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1778860692172
        },
        {
            "id": 300329,
            "sysLanguage": "en",
            "type": 1,
            "imageUrl": "",
            "title": "【🎉 Welcome to Dhani.win】",
            "content": "Welcome to Dhani.win — where wealth happens.\nBuilt on a legacy of trusted reputation and sincere service, Dhani.win is one of India’s leading online gaming platforms, created for real players and powered by one of the strongest reward systems in the market.\nLog in every day to receive a mystery bonus and start your journey with extra luck!",
            "sort": 333,
            "jumpUrl": "",
            "buttonTxt": "",
            "messageJumpType": 0,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1779383426274
        },
        {
            "id": 300333,
            "sysLanguage": "en",
            "type": 1,
            "imageUrl": "",
            "title": "【💰 Deposit & Withdrawal Notice】",
            "content": "At Dhani.win, all deposits are credited instantly.Withdrawals may occasionally be delayed due to security checks or peak traffic, but every transaction is safe and secure.\nIf your deposit has not arrived or your withdrawal was unsuccessful, please click the Self-Service Support Center to submit a ticket. Most cases are usually processed within 10 minutes.",
            "sort": 222,
            "jumpUrl": "",
            "buttonTxt": "",
            "messageJumpType": 0,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1779383190529
        },
        {
            "id": 300345,
            "sysLanguage": "en",
            "type": 1,
            "imageUrl": "",
            "title": "【🔒 Security Reminder】",
            "content": "Always verify you are accessing the official website to avoid scams or fake links. You can confirm the authenticity of any link through www.dhani.link. Protect your account and ensure a safe and secure gaming experience at all times.",
            "sort": 111,
            "jumpUrl": "",
            "buttonTxt": "",
            "messageJumpType": 0,
            "pageType": 0,
            "vendorCode": "",
            "gameCode": "",
            "gameId": "",
            "customPopupId": 0,
            "lastUpdateTime": 1776074543093
        }
    ],
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serverTime": 1780332121931
}