<?php
require_once dirname(__DIR__) . '/_bootstrap.php';

$endpoint = 'Activity/GetListRechargeWheelRewardHistory';
$override = api_get_override($endpoint);
if ($override) {
    $decoded = api_json_decode_lenient((string) $override['content']);
    if ($decoded['ok']) {
        $payload = $decoded['data'];
        api_refresh_times($payload);
        api_emit($payload);
    }
}

$payload = [
        'data' => [
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGQG4SU',
                'rewardType' => 1,
                'rewardAmount' => 17,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGQG4SU',
                'rewardType' => 1,
                'rewardAmount' => 17,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG2DEON',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGYAFMA',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG8DH14',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGQGKW8',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGH1N5N',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGGNR3I',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGH1N5N',
                'rewardType' => 1,
                'rewardAmount' => 37,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGCFOGH',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG7S7HW',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGN43QU',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGWQVSQ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGVH2UC',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG4O21Y',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGVZ362',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGAJXFI',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGNBAM3',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGLMRXG',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGLMRXG',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGTSLON',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG8Y45C',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGUISPI',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGRKXS4',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGZTKBE',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG7UPK4',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGEQIEN',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGZGLMF',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIM3KA',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHG7MZ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'IAMGAMER',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIKQCY',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG2Q8SD',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGKENHV',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGFAKLV',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGPVGJZ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGNVVP7',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGT8TOQ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGWTAWR',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGXVXMP',
                'rewardType' => 2,
                'rewardAmount' => 1,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGXVXMP',
                'rewardType' => 1,
                'rewardAmount' => 56,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGSRT4L',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG9PJTT',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGZ3ST6',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGPFF27',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGUIO9K',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGVXAKQ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGGFOFE',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGKSZ2D',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIIVIK',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGNCORM',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGBOIGX',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGJBCVY',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGYUZSP',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG3BCES',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGBBATN',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGDIMSH',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIE1JF',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGLZ0RP',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG96A8I',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGLTJPJ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGASQ5N',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGPD3WK',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGLYALY',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGWKPMH',
                'rewardType' => 1,
                'rewardAmount' => 166,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGFMGCF',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHOPFV',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHOPFV',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGOPY5F',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIFCJZ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGFSA3K',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGFVE1M',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGRJWQC',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGBXPAL',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGVXLE9',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGKOPLS',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGBB2R8',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGGLUT0',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGI7FCI',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGVQ3YW',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGSFEHL',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGRV8AJ',
                'rewardType' => 1,
                'rewardAmount' => 16,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG1LTY7',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHPMTW',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHFLKC',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGZXK8P',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGHVA20',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGZCMZ6',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGIORL8',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG3C3AF',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGYBNII',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNG8T5CY',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGO02KE',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGNLM48',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGQSXFJ',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGY69VM',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGCVGL0',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGEHBS7',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'Arabinda',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
            [
                'tenantId' => 6006,
                'nickName' => 'MemberNNGEGLCC',
                'rewardType' => 1,
                'rewardAmount' => 6,
            ],
        ],
        'code' => 0,
        'msg' => 'Succeed',
        'msgCode' => 0,
        'serverTime' => 1780315914686,
    ];

api_refresh_times($payload);
api_emit($payload);
